<?php
$admin_lang = $_SESSION['admin_lang'] ?? 'en';

$admin_t = [
    'en' => [
        // Nav
        'dashboard'   => 'Dashboard',
        'products'    => 'Products',
        'categories'  => 'Categories',
        'orders'      => 'Orders',
        'coupons'     => 'Coupons',
        'reviews'     => 'Reviews',
        'messages'    => 'Messages',
        'customers'   => 'Customers',
        'workers'     => 'Workers',
        'create_worker' => 'Create Worker',
        'new_worker'    => 'New Worker',
        'full_name'     => 'Full name',
        'phone_optional'=> 'Phone (optional)',
        'create'        => 'Create',
        'reports'     => 'Reports',
        'notifications'=> 'Notifications',
        'broadcast'   => 'Broadcast',
        'themes'      => 'Themes',
        'settings'    => 'Settings',
        'profile'     => 'My Profile',
        'view_site'   => 'View Site',
        'logout'      => 'Logout',
        // CRUD
        'add_products'=> 'Add Products',
        'new_product' => 'New Product',
        'edit_product'=> 'Edit Product',
        'add_category'=> 'Add Category',
        'new_category'=> 'New Category',
        'edit_category'=> 'Edit Category',
        'add_coupon'  => 'Add Coupon',
        'save'        => 'Save',
        'cancel'      => 'Cancel',
        'delete'      => 'Delete',
        'delete_order'=> 'Delete Order',
        'delete_all'  => 'Delete All',
        'update'      => 'Update',
        'view'        => 'View',
        'back'        => 'Back',
        'search'      => 'Search',
        'send'        => 'Send Notification',
        'unlock'      => 'Unlock',
        'verify'      => 'Verify',
        'mark_all_read'=> 'Mark All Read',
        // Table headers
        'photo'       => 'Photo',
        'id'          => 'ID',
        'name'        => 'Name',
        'slug'        => 'Slug',
        'price'       => 'Price',
        'discount'    => 'Discount',
        'quantity'    => 'Quantity',
        'brand'       => 'Brand',
        'category'    => 'Category',
        'status'      => 'Status',
        'featured'    => 'Featured',
        'new_arrival' => 'New Arrival',
        'sizes'       => 'Sizes',
        'colors'      => 'Colors',
        'description' => 'Description',
        'image'       => 'Image',
        'action'      => 'Action',
        'code'        => 'Code',
        'type'        => 'Type',
        'value'       => 'Value',
        'used'        => 'Used',
        'expires'     => 'Expires',
        'product'     => 'Product',
        'user'        => 'User',
        'rating'      => 'Rating',
        'review'      => 'Review',
        'subject'     => 'Subject',
        'date'        => 'Date',
        'read'        => 'Read',
        'customer'    => 'Customer',
        'email'       => 'Email',
        'phone'       => 'Phone',
        'total'       => 'Total',
        'payment'     => 'Payment',
        'placed'      => 'Placed',
        'items'       => 'Items',
        'month'       => 'Month',
        'revenue'     => 'Revenue',
        // Statuses
        'active'      => 'Active',
        'inactive'    => 'Inactive',
        'draft'       => 'Draft',
        'published'   => 'Published',
        'archived'    => 'Archived',
        'approved'    => 'Approved',
        'pending'     => 'Pending',
        'new'         => 'New',
        'online'      => 'Online',
        'offline'     => 'Offline',
        'make_worker' => 'Make Worker',
        'make_worker_confirm' => 'Make this customer a worker?',
        'worker'      => 'Worker',
        // Sort options
        'newest'      => 'New to Old',
        'oldest'      => 'Old to New',
        'name_az'     => 'A to Z',
        'name_za'     => 'Z to A',
        // Dashboard
        'recent_orders' => 'Recent Orders',
        'no_orders'   => 'No orders yet.',
        'low_stock'   => 'Low Stock Products',
        'left'        => 'left',
        'well_stocked'=> 'All products well stocked.',
        // Products
        'no_products' => 'No products found',
        'name_en'     => 'Name (EN)',
        'name_sw'     => 'Name (SW)',
        'desc_en'     => 'Description (EN)',
        'desc_sw'     => 'Description (SW)',
        'discount_price'=> 'Discount Price',
        'drop_images'  => 'Click or drop product images here',
        'drop_hint'    => 'Select multiple images at once — each becomes a product entry',
        'fill_ai'      => 'Fill with AI',
        'fill_all_ai'  => 'Fill All with AI',
        'save_all'     => 'Save All Products',
        'saving'       => 'Saving...',
        'deleting'     => 'Deleting...',
        'name_required'=> 'Name is required',
        'dup_image'    => 'Duplicate image',
        'notify_customers'=> 'Notify Customers',
        'broadcast_btn'=> 'Broadcast',
        // Categories
        'no_category'  => 'None',
        // Orders
        'order'       => 'Order',
        'customer_label'=> 'Customer:',
        'email_label'  => 'Email:',
        'phone_label'  => 'Phone:',
        'total_label'  => 'Total:',
        'volume_discount'=> 'Volume Discount:',
        'status_label' => 'Status:',
        'payment_label'=> 'Payment:',
        'placed_label' => 'Placed:',
        'delivery_label'=> 'Delivery:',
        'pickup'       => 'Pick up at shop',
        'delivery'     => 'Delivery',
        'update_status'=> 'Update Status',
        'delete_confirm'=> 'Permanently delete this order?',
        // Coupons
        'percent'     => '%',
        'fixed'       => 'Fixed',
        // Messages
        'no_messages' => 'No messages',
        // Customers
        'total_customers'=> 'Total Customers',
        'notif_eligible'=> 'Eligible',
        'notif_sent'   => 'Sent',
        'notif_failed' => 'Failed',
        'joined'       => 'Joined',
        'no_customers' => 'No customers found.',
        'in_app'       => 'In-App',
        'sms'          => 'SMS',
        'online_now'   => 'Online Now',
        // Reports
        'daily_sales'  => 'Daily Sales (7 days)',
        'monthly_sales'=> 'Monthly Sales',
        // Notifications
        'received'     => 'Received',
        'sent_broadcasts'=> 'Sent Broadcasts',
        'no_notifications'=> 'No received notifications.',
        'no_broadcasts' => 'No broadcast notifications sent yet.',
        'loading'      => 'Loading...',
        'notif_title'  => 'Notifications',
        // Broadcast
        'broadcast_title'=> 'Broadcast Notification',
        'preparing_for'=> 'Preparing notification for',
        'title_label'  => 'Title',
        'message_label'=> 'Message',
        'product_link' => 'Product Link',
        'optional'     => 'optional',
        'link_appended'=> 'Will be appended to the notification message',
        'recipients'   => 'Recipients',
        'all_users'    => 'All Users',
        'all_customers'=> 'All Customers',
        'opted_in'     => 'Only Opted-In Customers',
        'admins_only'  => 'Admins Only',
        'channels'     => 'Channels',
        'email_channel'=> 'Email',
        // Settings
        'settings_locked'=> 'Sensitive sections (Payment, SMTP, SMS) are locked.',
        'verify_unlock' => 'Verify admin password to unlock.',
        'general'      => 'General',
        'site_name'    => 'Site Name',
        'currency'     => 'Currency',
        'tax_rate'     => 'Tax Rate (%)',
        'shipping_threshold'=> 'Shipping Threshold (TZS)',
        'shipping_hint'=> 'Orders below this amount pay default rate',
        'rate_below'   => 'Rate Below (%)',
        'rate_above'   => 'Rate Above (%)',
        'free_shipping'=> 'Free Shipping Min',
        'default_payment'=> 'Default Payment',
        'azampay'      => 'AzamPay',
        'azampay_desc' => 'Mobile money payments via AzamPay (M-Pesa, Airtel, Tigo, HaloPesa)',
        'client_id'    => 'Client ID',
        'client_secret'=> 'Client Secret',
        'app_name'     => 'App Name (Token)',
        'environment'  => 'Environment',
        'sandbox'      => 'Sandbox',
        'production'   => 'Production',
        'callback_url' => 'Callback URL',
        'return_url'   => 'Return URL',
        'smtp_settings'=> 'Email (SMTP) Settings',
        'smtp_desc'    => 'Used for PHPMailer (password resets, order updates, contact notifications)',
        'smtp_host'    => 'SMTP Host',
        'smtp_username'=> 'SMTP Username',
        'smtp_password'=> 'SMTP Password',
        'encryption'   => 'Encryption',
        'port'         => 'Port',
        'sms_settings' => 'SMS Settings',
        'sms_desc'     => 'Used for SMS notifications (order updates, alerts)',
        'api_key'      => 'API Key',
        'secret_key'   => 'Secret Key',
        'sender_id'    => 'Sender ID',
        'beem'         => 'Beem Payments',
        'beem_desc'    => 'Mobile money payments via Beem Payment Checkout (M-Pesa, Airtel, Tigo, HaloPesa)',
        'pay_api_key'  => 'Payment API Key',
        'pay_secret_key'=> 'Payment Secret Key',
        'ref_prefix'   => 'Reference Prefix',
        'pawapay'      => 'PawaPay',
        'pawapay_desc' => 'Mobile money payments via PawaPay (M-Pesa, Airtel, Tigo, Halotel — Tanzania & Africa).',
        'api_token'    => 'API Token',
        'token_hint'   => 'Paste API token from PawaPay dashboard',
        'sandbox_ip'   => 'Sandbox IP to Whitelist',
        'stakaba'      => 'Stakaba (Cards)',
        'stakaba_desc' => 'Card payments via Stakaba (Visa, Mastercard).',
        'stakaba_hint' => 'sk_test_... or sk_live_...',
        'volume_tiers' => 'Volume Discount Tiers',
        'tiers_desc'   => 'Automatic discounts based on total cart quantity. Applied before coupons.',
        'min_qty'      => 'Min Qty',
        'max_qty'      => 'Max Qty',
        'discount_pct' => 'Discount (%)',
        'add_tier'     => 'Add Tier',
        'save_settings'=> 'Save All Settings',
        'verify_title' => 'Verify Admin Password',
        'verify_desc'  => 'Enter your admin password to unlock sensitive settings.',
        'wrong_password'=> 'Wrong password. Try again.',
        // Profile
        'new_password' => 'New Password',
        'keep_current' => 'leave empty to keep current',
        'confirm_password'=> 'Confirm Password',
        // Themes
        'theme_guide' => 'Welcome to Theme Settings! Customize your store\'s look below.

• Quick Styles — Pick colors for background, text, buttons, navbar & cards using the visual pickers. Switch between Light Mode and Dark Mode to set separate colors for each.

• Decorations & Effects — Add snowflakes, confetti, or falling stars for special occasions. Toggle the themed banner to show a message at the top of the page.

Tip: Click "Preview Mode" from the themes list to see your changes before publishing.',
        'theme_notes_label' => 'Note anything you want to remember about this theme',
        'theme_notes_placeholder' => 'e.g. Base fallback theme. Edit the Live theme to change what users see.',
    ],
    'sw' => [
        // Nav
        'dashboard'   => 'Dashibodi',
        'products'    => 'Bidhaa',
        'categories'  => 'Kategoria',
        'orders'      => 'Maagizo',
        'coupons'     => 'Kuponi',
        'reviews'     => 'Maoni',
        'messages'    => 'Ujumbe',
        'customers'   => 'Wateja',
        'workers'     => 'Wafanyakazi',
        'create_worker' => 'Unda Mfanyakazi',
        'new_worker'    => 'Mfanyakazi Mpya',
        'full_name'     => 'Jina kamili',
        'phone_optional'=> 'Simu (si lazima)',
        'create'        => 'Unda',
        'reports'     => 'Ripoti',
        'notifications'=> 'Arifa',
        'broadcast'   => 'Matangazo',
        'themes'      => 'Mandhari',
        'settings'    => 'Mipangilio',
        'profile'     => 'Wasifu Wangu',
        'view_site'   => 'Tazama Tovuti',
        'logout'      => 'Toka',
        // CRUD
        'add_products'=> 'Ongeza Bidhaa',
        'new_product' => 'Bidhaa Mpya',
        'edit_product'=> 'Hariri Bidhaa',
        'add_category'=> 'Ongeza Kategoria',
        'new_category'=> 'Kategoria Mpya',
        'edit_category'=> 'Hariri Kategoria',
        'add_coupon'  => 'Ongeza Kuponi',
        'save'        => 'Hifadhi',
        'cancel'      => 'Ghairi',
        'delete'      => 'Futa',
        'delete_order'=> 'Futa Agizo',
        'delete_all'  => 'Futa Zote',
        'update'      => 'Sasisha',
        'view'        => 'Tazama',
        'back'        => 'Nyuma',
        'search'      => 'Tafuta',
        'send'        => 'Tuma Arifa',
        'unlock'      => 'Fungua',
        'verify'      => 'Thibitisha',
        'mark_all_read'=> 'Weka Zote Kama Zimesomwa',
        // Table headers
        'photo'       => 'Picha',
        'id'          => 'ID',
        'name'        => 'Jina',
        'slug'        => 'Kiungo',
        'price'       => 'Bei',
        'discount'    => 'Punguzo',
        'quantity'    => 'Idadi',
        'brand'       => 'Chapa',
        'category'    => 'Kategoria',
        'status'      => 'Hali',
        'featured'    => 'Inayojulikana',
        'new_arrival' => 'Mpya',
        'sizes'       => 'Ukubwa',
        'colors'      => 'Rangi',
        'description' => 'Maelezo',
        'image'       => 'Picha',
        'action'      => 'Tenda',
        'code'        => 'Msimbo',
        'type'        => 'Aina',
        'value'       => 'Thamani',
        'used'        => 'Imetumika',
        'expires'     => 'Inaisha',
        'product'     => 'Bidhaa',
        'user'        => 'Mtumiaji',
        'rating'      => 'Ukadiriaji',
        'review'      => 'Maoni',
        'subject'     => 'Kichwa',
        'date'        => 'Tarehe',
        'read'        => 'Imesomwa',
        'customer'    => 'Mteja',
        'email'       => 'Barua pepe',
        'phone'       => 'Simu',
        'total'       => 'Jumla',
        'payment'     => 'Malipo',
        'placed'      => 'Iliwekwa',
        'items'       => 'Bidhaa',
        'month'       => 'Mwezi',
        'revenue'     => 'Mapato',
        // Statuses
        'active'      => 'Inatumika',
        'inactive'    => 'Haifanyi kazi',
        'draft'       => 'Rasimu',
        'published'   => 'Imechapishwa',
        'archived'    => 'Imehifadhiwa',
        'approved'    => 'Imeidhinishwa',
        'pending'     => 'Inasubiri',
        'new'         => 'Mpya',
        'online'      => 'Mtandaoni',
        'offline'     => 'Nje ya mtandao',
        'make_worker' => 'Fanya Mfanyakazi',
        'make_worker_confirm' => 'Fanya mteja huyu kuwa mfanyakazi?',
        'worker'      => 'Mfanyakazi',
        // Sort options
        'newest'      => 'Mpya hadi ya Zamani',
        'oldest'      => 'Zamani hadi Mpya',
        'name_az'     => 'A hadi Z',
        'name_za'     => 'Z hadi A',
        // Dashboard
        'recent_orders' => 'Maagizo ya Hivi Karibuni',
        'no_orders'   => 'Hakuna maagizo bado.',
        'low_stock'   => 'Bidhaa Zilizopungua',
        'left'        => 'zimebaki',
        'well_stocked'=> 'Bidhaa zote zipo vizuri.',
        // Products
        'no_products' => 'Hakuna bidhaa zilizopatikana',
        'name_en'     => 'Jina (EN)',
        'name_sw'     => 'Jina (SW)',
        'desc_en'     => 'Maelezo (EN)',
        'desc_sw'     => 'Maelezo (SW)',
        'discount_price'=> 'Bei ya Punguzo',
        'drop_images'  => 'Bofya au uweke picha za bidhaa hapa',
        'drop_hint'    => 'Chagua picha nyingi mara moja — kila picha inakuwa bidhaa',
        'fill_ai'      => 'Jaza kwa AI',
        'fill_all_ai'  => 'Jaza Zote kwa AI',
        'save_all'     => 'Hifadhi Bidhaa Zote',
        'saving'       => 'Inahifadhi...',
        'deleting'     => 'Inafuta...',
        'name_required'=> 'Jina linahitajika',
        'dup_image'    => 'Picha inayorudiwa',
        'notify_customers'=> 'Wajulishe Wateja',
        'broadcast_btn'=> 'Matangazo',
        // Categories
        'no_category'  => 'Hakuna',
        // Orders
        'order'       => 'Agizo',
        'customer_label'=> 'Mteja:',
        'email_label'  => 'Barua pepe:',
        'phone_label'  => 'Simu:',
        'total_label'  => 'Jumla:',
        'volume_discount'=> 'Punguzo la Kiasi:',
        'status_label' => 'Hali:',
        'payment_label'=> 'Malipo:',
        'placed_label' => 'Iliwekwa:',
        'delivery_label'=> 'Uwasilishaji:',
        'pickup'       => 'Kuchukua dukani',
        'delivery'     => 'Uwasilishaji',
        'update_status'=> 'Sasisha Hali',
        'delete_confirm'=> 'Futa agizo hili kabisa?',
        // Coupons
        'percent'     => 'Asilimia',
        'fixed'       => 'Imewekwa',
        // Messages
        'no_messages' => 'Hakuna ujumbe',
        // Customers
        'total_customers'=> 'Jumla ya Wateja',
        'notif_eligible'=> 'Wanaostahiki',
        'notif_sent'   => 'Imetumwa',
        'notif_failed' => 'Imeshindwa',
        'joined'       => 'Alijiunga',
        'no_customers' => 'Hakuna wateja waliopatikana.',
        'in_app'       => 'Ndani ya programu',
        'sms'          => 'SMS',
        'online_now'   => 'Mtandaoni Sasa',
        // Reports
        'daily_sales'  => 'Mauzo ya Kila Siku (siku 7)',
        'monthly_sales'=> 'Mauzo ya Kila Mwezi',
        // Notifications
        'received'     => 'Zilizopokelewa',
        'sent_broadcasts'=> 'Matangazo yaliyotumwa',
        'no_notifications'=> 'Hakuna arifa zilizopokelewa.',
        'no_broadcasts' => 'Hakuna matangazo yaliyotumwa bado.',
        'loading'      => 'Inapakia...',
        'notif_title'  => 'Arifa',
        // Broadcast
        'broadcast_title'=> 'Matangazo ya Arifa',
        'preparing_for'=> 'Inatayarisha arifa kwa',
        'title_label'  => 'Kichwa',
        'message_label'=> 'Ujumbe',
        'product_link' => 'Kiungo cha Bidhaa',
        'optional'     => 'si lazima',
        'link_appended'=> 'Itaongezwa kwenye ujumbe wa arifa',
        'recipients'   => 'Wapokeaji',
        'all_users'    => 'Watumiaji Wote',
        'all_customers'=> 'Wateja Wote',
        'opted_in'     => 'Wateja Waliochagua Tu',
        'admins_only'  => 'Wasimamizi Pekee',
        'channels'     => 'Njia',
        'email_channel'=> 'Barua pepe',
        // Settings
        'settings_locked'=> 'Sehemu nyeti (Malipo, SMTP, SMS) zimefungwa.',
        'verify_unlock' => 'Thibitisha nenosiri la msimamizi ili kufungua.',
        'general'      => 'Mkuu',
        'site_name'    => 'Jina la Tovuti',
        'currency'     => 'Sarafu',
        'tax_rate'     => 'Kiwango cha Kodi (%)',
        'shipping_threshold'=> 'Kiwango cha Usafirishaji (TZS)',
        'shipping_hint'=> 'Maagizo chini ya kiasi hiki yanalipa kiwango cha msingi',
        'rate_below'   => 'Kiwango Chini ya (%)',
        'rate_above'   => 'Kiwango Juu ya (%)',
        'free_shipping'=> 'Kiwango cha Usafirishaji Bure',
        'default_payment'=> 'Malipo Msingi',
        'azampay'      => 'AzamPay',
        'azampay_desc' => 'Malipo ya simu kwa njia ya AzamPay (M-Pesa, Airtel, Tigo, HaloPesa)',
        'client_id'    => 'Kitambulisho cha Mteja',
        'client_secret'=> 'Siri ya Mteja',
        'app_name'     => 'Jina la Programu (Token)',
        'environment'  => 'Mazingira',
        'sandbox'      => 'Sanduku la Majaribio',
        'production'   => 'Uzalishaji',
        'callback_url' => 'URL ya Kurudi',
        'return_url'   => 'URL ya Kurejea',
        'smtp_settings'=> 'Mipangilio ya Barua pepe (SMTP)',
        'smtp_desc'    => 'Inatumika kwa PHPMailer (kuweka upya nenosiri, sasisho la maagizo, arifa za mawasiliano)',
        'smtp_host'    => 'Seva ya SMTP',
        'smtp_username'=> 'Jina la mtumiaji la SMTP',
        'smtp_password'=> 'Nenosiri la SMTP',
        'encryption'   => 'Usimbaji fiche',
        'port'         => 'Bandari',
        'sms_settings' => 'Mipangilio ya SMS',
        'sms_desc'     => 'Inatumika kwa arifa za SMS (sasisho la maagizo, tahadhari)',
        'api_key'      => 'Ufunguo wa API',
        'secret_key'   => 'Ufunguo wa Siri',
        'sender_id'    => 'Kitambulisho cha Mtumaji',
        'beem'         => 'Malipo ya Beem',
        'beem_desc'    => 'Malipo ya simu kwa njia ya Beem (M-Pesa, Airtel, Tigo, HaloPesa)',
        'pay_api_key'  => 'Ufunguo wa API ya Malipo',
        'pay_secret_key'=> 'Ufunguo wa Siri wa Malipo',
        'ref_prefix'   => 'Kiambishi awali cha Kumbukumbu',
        'pawapay'      => 'PawaPay',
        'pawapay_desc' => 'Malipo ya simu kwa njia ya PawaPay (M-Pesa, Airtel, Tigo, Halotel).',
        'api_token'    => 'Tokeni ya API',
        'token_hint'   => 'Bandika tokeni ya API kutoka dashibodi ya PawaPay',
        'sandbox_ip'   => 'Anwani ya IP ya Sanduku la Majaribio',
        'stakaba'      => 'Stakaba (Kadi)',
        'stakaba_desc' => 'Malipo ya kadi kwa njia ya Stakaba (Visa, Mastercard).',
        'stakaba_hint' => 'sk_test_... au sk_live_...',
        'volume_tiers' => 'Viwango vya Punguzo la Kiasi',
        'tiers_desc'   => 'Punguzo la kiotomatiki kulingana na jumla ya idadi ya bidhaa kwenye rukwama. Inatumika kabla ya kuponi.',
        'min_qty'      => 'Kiasi cha Chini',
        'max_qty'      => 'Kiasi cha Juu',
        'discount_pct' => 'Punguzo (%)',
        'add_tier'     => 'Ongeza Kiwango',
        'save_settings'=> 'Hifadhi Mipangilio Yote',
        'verify_title' => 'Thibitisha Nenosiri la Msimamizi',
        'verify_desc'  => 'Weka nenosiri lako la msimamizi ili kufungua sehemu nyeti.',
        'wrong_password'=> 'Nenosiri si sahihi. Jaribu tena.',
        // Profile
        'new_password' => 'Nenosiri Mpya',
        'keep_current' => 'acha wazi ili kuweka lililopo',
        'confirm_password'=> 'Thibitisha Nenosiri',
        // Themes
        'theme_guide' => 'Karibu kwenye Mipangilio ya Mandhari! Badilisha mwonekano wa duka lako hapa.

• Quick Styles — Chagua rangi kwa mandhari ya nyuma, maandishi, vitufe, upau wa juu na kadi kwa kutumia viteua rangi. Badilisha kati ya Light Mode na Dark Mode kuweka rangi tofauti kwa kila hali.

• Mapambo na Athari — Ongeza theluji, confetti, au nyota zinazoanguka kwa matukio maalum. Washa bango la mandhari ili kuonesha ujumbe juu ya ukurasa.

Kidokezo: Bofya "Preview Mode" kutoka orodha ya mandhari ili kuona mabadiliko yako kabla ya kuchapisha.',
        'theme_notes_label' => 'Andika chochote unachotaka kukumbuka kuhusu mandhari haya',
        'theme_notes_placeholder' => 'mf. Mandhari ya msingi. Hariri mandhari ya Live ili kubadilisha kile watumiaji wanachokiona.',
    ],
];

function __t($key, $fallback = null) {
    global $admin_t, $admin_lang;
    return $admin_t[$admin_lang][$key] ?? $admin_t['en'][$key] ?? $fallback ?? $key;
}
